### ISSUE TITLE
Updating Wiki.js to 2.5.126 Broke Integration

### ISSUE THREAD

**Issue by rcmurphy** [pvyParts/allianceauth-wiki-js#1]
Hi!

I upgraded our wiki to version 2.5.126 from 2.4.107 and am now encountering 500 errors whenever I try to use any part of Alliance Auth that calls out to the wiki. Any help would be appreciated!

**Comment by pvyParts** [comment]
No probs, I'll update mine and have a look

**Comment by rcmurphy** [comment]
Thank you so much!
Relevant Error Message:
```
ERROR:wikijs.views:Failed to install custom Wiki.JS password for user XXX
ERROR:root:'NoneType' object is not subscriptable
```

**Comment by pvyParts** [comment]
Confirmed on my box now to fix it.

**Comment by pvyParts** [comment]
Update your wiki again to `2.5.136` issue was with the wiki.
