### ISSUE TITLE
 Cannot read property 'groups' of undefined

### ISSUE THREAD

**Issue by paulipa** [pvyParts/allianceauth-wiki-js#2]
Trying to activate the wiki service returns ` Cannot read property 'groups' of undefined` on wiki server. It used to work back in the days so im not sure if something has changed on auth side or on wiki side

**Comment by pvyParts** [comment]
What version of the plugin and what version of wiki?

**Comment by paulipa** [comment]
Currently running on 2.5.126 wiki and 0.0.2 (just pulled latest from git to test)

**Comment by pvyParts** [comment]
I have update the wiki too those versions had API bugs

**Comment by paulipa** [comment]
updating to Wiki.js 2.5.144 seems to fix the issue! Thank you :)
